language: ruby
rvm:
  - 2.5.1

sudo: required

services:
  - docker

before_install:
  - export RAILS_ENV=test
  - gem install bundler

before_script:
  - bundle install --jobs=3 --retry=3

script:
  - bundle exec rubocop
  
  - bundle exec rails db:setup
  - bundle exec rspec

deploy:
  provider: script
  script: bash deploy.sh
  on:
    branch: master
