language: ruby
rvm:
  - 2.5.1

before_install:
  - export RAILS_ENV=test
  - gem install bundler
  - bundle install --jobs=3 --retry=3

stages:
  - lint
  - test
  - name: deploy
    if: branch = master 


jobs:
  include:
    - stage: lint
    script:
      - bundle exec rubocop
    
    - stage: test
    script:    
      - bundle exec rails db:setup
      - bundle exec rspec
    
    - stage: deploy
    script:
      - echo 'test'
