version: '3'
services:
  
  web:
    image: "ozkar99/tools:${REF:?err}"
    env_file:
      - ./credentials.env
    volumes:
      - ./db:/tools/db
    ports:
      - "80:3000"
    depends_on:
      - migrate
    command: bundle exec rails s -e production

  migrate:
    image: "ozkar99/tools:${REF:?err}"
    env_file:
      - ./credentials.env
    volumes:
      - ./db:/tools/db
    command: bundle exec rails db:migrate
