version: '3'
services:
  
  web:
    image: "ozkar99/tools:${REF:-latest}"
    env_file:
      - credentials.env
    command: bundle exec rails s -e production

  migrate:
    image: "ozkar99/tools:${REF:-latest}"
    env_file:
      - credentials.env
    depends_on:
      - database
    command: bundle exec rails db:migrate

  database:
    image: postgres:10
    env_file:
      - credentials.env
    environment:
      POSTGRES_USER: tools
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
 
  caddy:
    image: abiosoft/caddy
    volumes:
      - ./Caddyfile:/etc/Caddyfile:ro
    ports:
      - "443:443"