version: '3'
services:
  
  web:
    image: tools
    env_file:
      - ./credentials.env
    command: bundle exec rails s -e production

  migrate:
    build: .
    image: tools
    env_file:
      - ./credentials.env
    depends_on:
      - database
    command: bundle exec rails db:migrate

  database:
    image: postgres:9.5
    env_file:
      - ./credentials.env
    environment:
      - "POSTGRES_USER=tools"
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
 
  caddy:
    image: abiosoft/caddy
    volumes:
      - ./Caddyfile:/etc/Caddyfile:ro
    ports:
      - "80:80"
      - "443:443"
