version: '3'
services:
  
  web:
    image: "ozkar99/tools:${REF:?err}"
    env_file:
      - ./credentials.env
    ports:
      - "80:3000"
    depends_on:
      - migrate
    command: bundle exec rails s -e production

  migrate:
    image: "ozkar99/tools:${REF:?err}"
    env_file:
      - ./credentials.env
    depends_on:
      - database
    command: bundle exec rails db:migrate

  database:
    image: postgres:9.5
    env_file:
      - ./credentials.env
    environment:
      - "POSTGRES_USER=tools"
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
